#!/usr/bin/env bash

set -xeuo pipefail

# [PPIndentWidth](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#ppindentwidth)
clang-tidy --fix --format-style='{BasedOnStyle: llvm, IndentWidth: 8, PPIndentWidth: 3}' "${REPO_ROOT}"/Unity/src/unity.c "$1" -- -I "${REPO_ROOT}"/Unity/src "$1"
