#!/usr/bin/env bash

set -xeuo pipefail

# [How do I get the directory where a Bash script is located from within the script itself?](https://stackoverflow.com/a/246128)
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

find . -name 'run*' -or -name '*.c' -or -name '*.h' | entr -c "${SCRIPT_DIR}"/scripts/compile "$1" && "${SCRIPT_DIR}"/scripts/run "$1"
