#!/usr/bin/env bash

set -xeuo pipefail

TMPDIR="${TMPDIR:-/tmp}"

# [Clang: Locally Disabling Warnings](https://embeddedartistry.com/blog/2017/06/07/warnings-weverything-and-the-kitchen-sink/#clang-locally-disabling-warnings)
clang \
    -std=c2x \
    -g3 \
    -O0 \
    -Weverything `# [Clang: -Weverything](https://embeddedartistry.com/blog/2017/06/07/warnings-weverything-and-the-kitchen-sink/#clang-weverything)` \
    -Werror \
    -Wno-pre-c23-compat \
    -Wno-unsafe-buffer-usage \
    -Wno-declaration-after-statement \
    -Wno-padded \
    -Wno-vla \
    -ferror-limit=1 \
    -fsanitize=address,undefined,leak,integer \
    -I "${REPO_ROOT}"/Unity/src "$1" "${REPO_ROOT}"/Unity/src/unity.c \
    -o "${TMPDIR}/a.out"

if [[ "${STRICT_RUNLOOP_CHECKS:-false}" != false ]]; then
    # [Which of the three mutually exclusive Clang sanitizers should I default to?](https://stackoverflow.com/questions/50364533/which-of-the-three-mutually-exclusive-clang-sanitizers-should-i-default-to)
    clang -fsanitize=memory -I "${REPO_ROOT}"/Unity/src "$1" "${REPO_ROOT}"/Unity/src/unity.c -o "${TMPDIR}/a.out"
    clang -fsanitize=thread -I "${REPO_ROOT}"/Unity/src "$1" "${REPO_ROOT}"/Unity/src/unity.c -o "${TMPDIR}/a.out"
fi
clang -std=c2x -g3 -O0 -I "${REPO_ROOT}"/Unity/src "$1" "${REPO_ROOT}"/Unity/src/unity.c -o "${TMPDIR}/a.out"
