#!/usr/bin/env bash

set -xeuo pipefail

# [How do I get the directory where a Bash script is located from within the script itself?](https://stackoverflow.com/a/246128)
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

TMPDIR="${TMPDIR:-/tmp}"

# [Clang: -Weverything](https://embeddedartistry.com/blog/2017/06/07/warnings-weverything-and-the-kitchen-sink/#clang-weverything)
# [Clang: Locally Disabling Warnings](https://embeddedartistry.com/blog/2017/06/07/warnings-weverything-and-the-kitchen-sink/#clang-locally-disabling-warnings)
# [Which of the three mutually exclusive Clang sanitizers should I default to?](https://stackoverflow.com/questions/50364533/which-of-the-three-mutually-exclusive-clang-sanitizers-should-i-default-to)
clang -std=c2x -g3 -O0 -Weverything -Werror -Wno-pre-c23-compat -Wno-unsafe-buffer-usage -Wno-declaration-after-statement -ferror-limit=1 -fsanitize=address,undefined,leak,integer -I "${SCRIPT_DIR}"/Unity/src "$1" "${SCRIPT_DIR}"/Unity/src/unity.c -o "${TMPDIR}/a.out"
#-fsanitize=thread,memory
gdb -q -ex run /tmp/a.out
